global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram-bot'

receivers:
- name: 'telegram-bot'
  telegram_configs:
  - bot_token: '8976619966:AAHSsnXHyovk6QMF5Gc0luImnxw5rkp6j_Y'
    chat_id: 379967642                                      
    parse_mode: 'HTML'
    message: |
      <b>[Alert] {{ .Status | toUpper }}</b>
      📌 <b>Назва:</b> {{ .GroupLabels.alertname }}
      🔥 <b>Рівень:</b> {{ .CommonLabels.severity }}
      📖 <b>Опис:</b> {{ .CommonAnnotations.description }}