apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/uacomedian/Homework-DAN-IT
    targetRevision: HEAD
    path: Final-project/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true