apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: uacomedian/devops-app:1246a646e2f9c707ca5d8015d491655c2e5736ed
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name