---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-random
  template:
    metadata:
      labels:
        app: python-random
    spec:
      containers:
      - name: app
        image: uacomedian/python-random:v1
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: random-string-service
spec:
  type: LoadBalancer
  selector:
    app: python-random
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082